ready for 2.2 release

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,6 +1,6 @@
 dnl Process this file with autoconf to produce a configure script.
 
-AC_INIT(jxta, 2.1)
+AC_INIT(jxta-c, 2.2.0)
 AC_CONFIG_SRCDIR(configure.in)
 AC_CONFIG_AUX_DIR(conftools)
 AC_CANONICAL_TARGET
@@ -12,6 +12,8 @@ AC_ISC_POSIX
 AC_PROG_CC
 AM_PROG_CC_STDC
 AC_HEADER_STDC
+AC_LIBTOOL_DLOPEN
+AC_PROG_LIBTOOL
 
 # Here is an example test for a certain header
 # foo.h that is not in the path that we might want in the 
@@ -29,42 +31,73 @@ AC_HEADER_STDC
 #exit 0
 #])
 
+AC_CHECK_LIB(expat,XML_ParserCreate,[],[
+ echo "The expat library for XML processing is required by JXTA" 
+ exit 0
+])
+
+#AC_CHECK_LIB(crypto,BN_new,[],[
+#    echo "The OpenSSL library for basic cryptographic functions is required by JXTA" 
+#    exit 0
+#])
+
+case $host_os in
+  solaris*)
+    AC_CHECK_LIB(socket,getaddrinfo,[],[
+     echo "The socket library for emulation of BSD Sockets is required by JXTA"
+     exit 0
+    ])
+    ;;
+  darwin*)
+    ;;
+  *)
+#    AC_CHECK_LIB(crypt,crypt_r,[],[
+#     echo "The crypt library for basic cryptographic functions is required by JXTA" 
+#     exit 0
+#    ])
+    ;;
+esac
+
 AC_ARG_ENABLE([debug],
-  AC_HELP_STRING([--enable-debug], [enable debug log]),
+  AC_HELP_STRING([--enable-debug], [Enable JXTA_LOG debugging display.]),
   [ac_enable_debug=$enableval], [ac_enable_debug=no])
 
-if test "x$ac_enable_debug" != "xno" ; then
+if test "x$ac_enable_debug" = "xyes" ; then
   CPPFLAGS="-DJXTA_LOG_ENABLE=1 $CPPFLAGS"
 fi
-  
-AC_ARG_WITH(dbm, 
-  AC_HELP_STRING([--with-dbm], [dbm type to use with apr]),
-  [
-    case "$withval" in
-    db)
-      dbtype='"DB"'
-      ;;
-    sdbm)
-      dbtype='"SDBM"'
-      ;;
-    *)
-      echo "invalid dbm, only db, sdbm are supported currently."
-      exit 0
-      ;;
-    esac
-  ], [
-    dbtype='"SDBM"'
-  ])
+
+AC_ARG_ENABLE([compression],
+  AC_HELP_STRING([--enable-compression], [Enable SRDI zlib compression.]),
+  [ac_enable_compression=$enableval], [ac_enable_compression=yes])
+
+if test "x$ac_enable_compression" = "xyes" ; then
+  CPPFLAGS="-DGZIP_ENABLED=1 $CPPFLAGS"
+fi
+
+AC_ARG_ENABLE([decompression],
+  AC_HELP_STRING([--enable-decompression], [Enable SRDI zlib decompression.]),
+  [ac_enable_decompression=$enableval], [ac_enable_decompression=yes])
+
+if test "x$ac_enable_decompression" = "xyes" ; then
+  CPPFLAGS="-DGUNZIP_ENABLED=1 $CPPFLAGS"
+fi
+
+AC_ARG_ENABLE([object-tracking],
+  AC_HELP_STRING([--enable-object-tracking], [enable object tracking logs]),
+  [ac_enable_object_tracking=$enableval], [ac_enable_object_tracking=no])
+
+if test "x$ac_enable_object_tracking" != "xno" ; then
+  CPPFLAGS="-DJXTA_OBJECT_TRACKING_ENABLE=1 $CPPFLAGS"
+fi
 
 AC_ARG_WITH(apr, 
   AC_HELP_STRING([--with-apr],
-    [to use jxta-c distributed libapr or specify your own.]),
-  [with_apr=$withval], [with_apr=yes])
+    [Specify the location of APR/APU to use.]),
+  [with_apr=$withval], [with_apr=no])
 
 case "$with_apr" in
   yes)
     apr_prefix="`pwd`/lib/apr"
-    dbtype='"SDBM"'
     ;;
   no | apr-config)
     apr_prefix=""
@@ -75,73 +108,160 @@ case "$with_apr" in
 esac
 
 if test -z $apr_prefix ; then
-  AC_PATH_PROG(apr_config, apr-config, "")
-
-  if test -z "$apr_config" ; then
-    echo "Cannot find apr-config, apr must be installed to build jxta"
-    exit 0
-  fi 
-
-  apr_includedir=`$apr_config --includedir`
-  apr_libs=`$apr_config --link-ld --libs`
-
-  AC_PATH_PROG(apu_config, apu-config, "")
-
-  if test -z "$apu_config" ; then
-    echo "Cannot find apu-config, apr must be installed to build jxta"
-    exit 0
-  fi 
-
-  apu_libs=`$apu_config --link-ld --libs`
+  AC_PATH_PROG(apr_config, apr-1-config, "")
 else
-  apr_includedir="$apr_prefix/include/apr-0"
-  apr_libs=" -L$apr_prefix/lib -lapr-0"
-  apu_libs=""
+  AC_PATH_PROG(apr_config, apr-1-config, "", [$apr_prefix/bin])
 fi
 
-AC_DEFINE_UNQUOTED(DBTYPE, $dbtype, [DBM type to use with libapr])
-APR_CPPFLAGS=" -I$apr_includedir"
-APR_LIBS="$apr_libs $apu_libs"
-AC_SUBST(APR_CPPFLAGS)
-AC_SUBST(APR_LIBS)
+if ! test -f "$apr_config" ; then
+  echo "Cannot find apr-1-config, apr must be installed to build JXTA"
+  exit 0
+fi 
 
-AC_CHECK_LIB(expat,XML_ParserCreate,[],[
- echo "The expat library for XML processing is required by jxta" 
- exit 0
-])
+apr_prefix="`$apr_config --prefix`"
 
-AC_CHECK_LIB(dl,dlopen,[],[
- echo "The dl library for dynamic linking is required by jxta" 
- exit 0
-])
-
-case $host_os in
-  solaris*)
-    AC_CHECK_LIB(socket,getaddrinfo,[],[
-     echo "The socket library for emulation of BSD Sockets is required by jxta"
-     exit 0
-    ])
+AC_ARG_WITH(apu,
+  AC_HELP_STRING([--with-apu],
+    [Specify the location of APU to use.]),
+  [with_apu=$withval], [with_apu=no])
+  
+case "$with_apu" in
+  yes)
+    apu_prefix="`pwd`/lib/apr-util"
     ;;
-  darwin*)
+  no | apu-config)
+    apu_prefix=""
     ;;
   *)
-#    AC_CHECK_LIB(crypt,crypt_r,[],[
-#     echo "The crypt library for basic cryptographic functions is required by jxta" 
-#     exit 0
-#    ])
+    apu_prefix=$with_apu
     ;;
 esac
 
-#if test $APR ; then
-#    echo "APR is set to $APR"
-#else
-#    AC_CHECK_LIB(apr, main, [echo "APR found"],
-#    [echo "APR not found"
-#     exit 0])
-#fi
+if test -z $apu_prefix ; then
+  AC_PATH_PROG(apu_config, apu-1-config, "", [$PATH:$apr_prefix/bin])
+else
+  AC_PATH_PROG(apu_config, apu-1-config, "", [$apu_prefix/bin])
+fi
 
+if ! test -f "$apu_config" ; then
+  echo "Cannot find apu-1-config, apr-util must be installed to build JXTA"
+  exit 0
+fi
 
-AC_LIBTOOL_DLOPEN
+apu_prefix="`$apu_config --prefix`"
+
+apr_cppflags=`$apr_config --cppflags --includes`
+apr_libs=`$apr_config --link-ld --libs`
+
+apu_cppflags=`$apu_config --includes`
+apu_libs=`$apu_config --link-ld --libs`
+
+APR_CPPFLAGS="$apr_cppflags $apu_cppflags"
+APR_LIBS="$apr_libs $apu_libs"
+
+AC_SUBST(APR_CPPFLAGS)
+AC_SUBST(APR_LIBS)
+
+CFLAGS="`$apr_config --cflags` $CFLAGS"
+
+dnl The modified libxml2 lib sits in the lib directory
+
+AC_ARG_WITH(libxml2, 
+  AC_HELP_STRING([--with-libxml2],
+    [Specify the location of libxml2 to use.]),
+  [with_libxml2=$withval], [with_libxml2=no])
+
+case "$with_libxml2" in
+  yes)
+    xml2_prefix="`pwd`/lib/libxml2/libxml2-2.6.19"
+    ;;
+  no | libxml2-config)
+    xml2_prefix=""
+    ;;
+  *)
+    xml2_prefix=$with_libxml2
+    ;;
+esac
+
+if test -z "$xml2_prefix" ; then  
+  AC_PATH_PROG(xml2_config, xml2-config, "")
+else
+  AC_PATH_PROG(xml2_config, xml2-config, "", [$xml2_prefix/bin])
+fi 
+
+if test -z "$xml2_config" ; then
+  echo "Cannot find xml2-config, libxml2 must be installed to build JXTA"
+  exit 0
+fi 
+
+xml2_prefix="`$xml2_config --prefix`"
+xml2_cppflags=" `$xml2_config --cflags` "
+XML2_CPPFLAGS=$xml2_cppflags
+xml2_libs=" `$xml2_config --libs` "
+XML2_LIBS=$xml2_libs
+
+AC_SUBST(XML2_CPPFLAGS)
+AC_SUBST(XML2_LIBS)
+
+dnl SQLite
+
+AC_ARG_WITH(sqlite, 
+  AC_HELP_STRING([--with-sqlite],
+    [Specify the location of SQLite to use.]),
+  [with_sqlite=$withval], [with_sqlite=no])
+
+case "$with_sqlite" in
+  no)
+    sqlite_prefix=""
+    ;;
+  *)
+    sqlite_prefix=$with_sqlite
+    ;;
+esac
+
+if test -n "$sqlite_prefix" ; then
+  sqlite_cflags=" -I$sqlite_prefix/include "
+  sqlite_libs=" -L$sqlite_prefix/lib -lsqlite3 "
+else
+  sqlite_cflags=" `pkg-config sqlite3 --cflags` "
+  sqlite_libs=" `pkg-config sqlite3 --libs` "
+  sqlite_prefix="`pkg-config --variable=prefix sqlite3`"
+fi 
+
+SQLITE_CPPFLAGS="$sqlite_cppflags"
+SQLITE_LIBS="$sqlite_libs"
+
+dnl OpenSSL
+
+AC_ARG_WITH(openssl, 
+  AC_HELP_STRING([--with-openssl],
+    [Specify the location of openssl lib to use.]),
+  [with_openssl=$withval], [with_openssl=no])
+
+case "$with_openssl" in
+  no)
+    openssl_prefix=""
+    ;;
+  *)
+    openssl_prefix=$with_openssl
+    ;;
+esac
+
+if test -n "$openssl_prefix" ; then
+  openssl_cflags=" -I$openssl_prefix/include "
+  openssl_libs=" -L$openssl_prefix/lib -lcrypto"
+else
+  openssl_cflags=" `pkg-config openssl --cflags` "
+  openssl_libs=" `pkg-config openssl --libs` "
+  openssl_prefix="`pkg-config --variable=prefix openssl`"
+fi 
+
+SQLITE_CPPFLAGS="$SQLITE_CPPFLAGS $openssl_cflags"
+SQLITE_LIBS="$SQLITE_LIBS $openssl_libs"
+
+AC_SUBST(SQLITE_CPPFLAGS)
+AC_SUBST(SQLITE_LIBS)
+
 AM_PROG_LIBTOOL
 
 dnl libjxta.4 has definitions for supporting automatic "jxta-config"
@@ -150,3 +270,29 @@ dnl macro should automatically create it.
 dnl AC_CREATE_GENERIC_CONFIG
 
 AC_OUTPUT([Makefile src/Makefile src/jpr/Makefile src/unicode/Makefile test/Makefile shell/Makefile tutorials/Makefile])
+
+# Pretty Messages (idea stolen from Ethereal)
+
+if test "x$ac_enable_debug" = "xyes" ; then
+	debug_message="yes"
+else
+	debug_message="no"
+fi
+
+if test "x$ac_enable_debug" = "xyes" ; then
+	debug_message="yes"
+else
+	debug_message="no"
+fi
+
+echo ""
+echo "JXTA has been configured with the following options:"
+echo "                  Debug enabled : $debug_message"
+echo "                  Compression enabled : $ac_enable_compression"
+echo "                  Decompression enabled : $ac_enable_decompression"
+echo "                  libxml2 Path : $xml2_prefix"
+echo "                  APR Path : $apr_prefix"
+echo "                  APU Path : $apu_prefix"
+echo "                  sqlite Path : $sqlite_prefix"
+echo "                  openssl Path : $openssl_prefix"
+
